version: '3'
services:
  db:
    image: mysql:8.4
    container_name: mysql
    restart: always
    volumes:
      - data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}", "-e", "SELECT 1"]
      timeout: 5s
      retries: 2

  nginx:
    build:
      context: server/nginx
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - user
      - groups


  user:
    build:
      context: server/user
      dockerfile: Dockerfile
    container_name: user
    restart: always
    volumes:
      - static:/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
        db:
          condition: service_healthy

  groups:
    build:
      context: server/groups
      dockerfile: Dockerfile
    container_name: groups
    restart: always
    volumes:
      - static:/static
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  telebot:
    build:
      context: client/telegram_bot
      dockerfile: Dockerfile
    container_name: telebot
    restart: always
    volumes:
      - static:/static
    ports:
      - 10000:10000
    expose:
      - 10000
    depends_on:
      - db
      - nginx

volumes:
  static:
  data: